language: node_js
node_js:
    - node
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script:
    - npm install
    - npm run build
    - npm run coverage
